### PR TITLE
1142 bug import profile links to wrong screen

### LINKED ISSUE #1142: [BUG] Import profile links to wrong screen
### Describe the Bug

There are inconsistencies in the import profile experience

### Expected experience

- [x] The link in the Popup menu should be "Import an existing profile" as per [the design](https://www.figma.com/design/ELsn1EA0ptswW1f21PZqWp/%F0%9F%9F%A2-Flow-Wallet?node-id=3014-14667&m=dev).
- [x] Change the link name from recoverprofile to 'import-profile'
- [x] That link should take the user directly to the import profile page
- [x] Add new profile in the settings should should a popup like on the profile popup menu with - Create new profile, and import and existing profile
- [x] The stepper on the import profile screen should not have a back button on step 1
- [x] The user should not be logged out when they go to the import profile screen

### Steps To Reproduce

as above

### Environment

```markdown
2.9.0
```

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #1142

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

File: apps/extension/src/background/controller/wallet.ts [hunk 1]
```diff
@@ -683,13 +683,14 @@ export class WalletController extends BaseController {
...
   lockAdd = async () => {
-    await keyringService.lock();
-    sessionService.broadcastEvent('accountsChanged', []);
-    sessionService.broadcastEvent('lock');
+    openIndexPage('welcome/importprofile?add=true');
+  };
+
+  // create profile here
+  createProfile = async () => {
     openIndexPage('welcome?add=true');
```
Comment (tombeckenham) [inline apps/extension/src/background/controller/wallet.ts]: Shouldn't that go to welcome/register?

File: apps/extension/src/ui/components/settings/add-profile-popup.tsx [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+const AddProfilePopup = ({ isOpen, onClose }: AddProfilePopupProps) => {
+  return (
+    <Drawer
+      anchor="bottom"
+      sx={{ zIndex: '1500 !important' }}
+      open={isOpen}
+      onClose={onClose}
+      transitionDuration={300}
+      PaperProps={{
```
Comment (tombeckenham) [inline apps/extension/src/ui/components/settings/add-profile-popup.tsx]: You should use the new slotProps - see https://mui.com/material-ui/migration/migrating-from-deprecated-apis/#paperprops

File: apps/extension/src/ui/components/profile/stories/profile-button.stories.tsx [hunk 3]
```diff
@@ -48,10 +48,10 @@ export const CreateProfile: Story = {
...
-export const RecoverProfile: Story = {
+export const ImportProfile: Story = {
   args: {
     icon: userCircleCheck,
-    text: 'Recover an existing profile',
-    onClick: async () => consoleLog('Recover profile clicked'),
+    text: 'Import an existing profile',
+    onClick: async () => consoleLog('Import profile clicked'),
   },
 };
```
Comment (tombeckenham) [inline apps/extension/src/ui/components/profile/stories/profile-button.stories.tsx:57]: Might be nice to add a profile-actions story. Should be super simple to show it all together

**Review by tombeckenham — APPROVED** [review]
