### PR TITLE
fixed: add optional currency code for coinlist to prevent extra render

### LINKED ISSUE #949: [TASK] Clean up multi-currency display
### Issue to be solved

The current currency is loaded every time in the CurrencyValue component. This slows down rendering and can cause glitches

### Suggest A Solution

- Store the currency code in the token info
- Use Intl format to display currency values
- Pass the currency code to the currency component

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #949  

## Summary of Changes

Passed the currency code and symbol from coinlist to the currencyValue component to avoid rerendering the component when loading the state multiple times.

## Need Regression Testing

Check the currency value in different components to see if anything changes

- [x] Yes
- [ ] No

## Risk Assessment

- [x] Low
- [ ] Medium
- [ ] High

### CODE REVIEW

File: src/ui/views/TokenDetail/CurrencyValue.tsx [hunk 1]
```diff
@@ -8,23 +8,27 @@ interface CurrencyValueProps {
...
 
 export const CurrencyValue: React.FC<CurrencyValueProps> = ({
   value,
   className,
   showCurrencyCode = true,
+  currencyCode,
+  currencySymbol,
 }) => {
+  //only use its values if props aren't provided
   const currency = useCurrency();
```
Comment (tombeckenham) [inline src/ui/views/TokenDetail/CurrencyValue.tsx]: Could we just make currencyCode and symbol required and remove the need for useCurrency? It just creates a tonne of listeners as every cell has one

**Review by tombeckenham — CHANGES_REQUESTED** [review]

**Review by tombeckenham — APPROVED** [review]
